/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import { GraphQLSchema } from 'graphql';

export function getSchema(): GraphQLSchema {
  return new GraphQLSchema({
    types: [],
  });
}
